// Steering Matrix — an effective steering table whose rows are GENERATED by calling
// /api/v1/dns/explain for each scenario (outcomes are never hard-coded). Partial
// evaluations never show a definitive platform, and expected shares are always labelled
// probabilistic. Accessible with steering.summary.read; full evaluation needs
// dns.explain.read (the API enforces this).
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, ApiError } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { networkPathForAsn } from '../topology/model';
import { SCENARIOS, scenarioToPrefill, type SteeringScenario } from '../steering/scenarios';
import type { EvaluationResult, ExplainResponse } from '../api/types';

type Status = 'Complete' | 'Partial' | 'Unavailable';

interface Row {
  scenario: SteeringScenario;
  status: Status;
  data?: ExplainResponse;
}

function platformLabels(ev: EvaluationResult, ids: string[]): string {
  return ids.map((id) => ev.answers.find((a) => a.id === id)?.deliveryPlatform ?? id).join(', ') || '—';
}

function statusOf(data: ExplainResponse | undefined, failed: boolean): Status {
  if (failed || !data) return 'Unavailable';
  return data.evaluation.complete ? 'Complete' : 'Partial';
}

export function Steering() {
  const { hasPermission } = useAuth();
  const navigate = useNavigate();
  const canExplain = hasPermission('dns.explain.read');

  const [rows, setRows] = useState<Row[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [country, setCountry] = useState('');
  const [net, setNet] = useState('');
  const [statusFilter, setStatusFilter] = useState<'' | Status>('');

  useEffect(() => {
    if (!canExplain) return;
    let active = true;
    Promise.allSettled(SCENARIOS.map((s) => api.explain(s.request)))
      .then((settled) => {
        if (!active) return;
        setRows(
          settled.map((r, i) => {
            const failed = r.status === 'rejected';
            const data = r.status === 'fulfilled' ? r.value : undefined;
            return { scenario: SCENARIOS[i], data, status: statusOf(data, failed) };
          }),
        );
      })
      .catch((e: unknown) => active && setError(e instanceof ApiError ? e.message : 'Failed to build the steering matrix.'));
    return () => {
      active = false;
    };
  }, [canExplain]);

  const filtered = useMemo(
    () =>
      (rows ?? []).filter(
        (row) =>
          (!country || row.scenario.country.toLowerCase().includes(country.toLowerCase())) &&
          (!net || `${row.scenario.asn} ${row.scenario.network}`.toLowerCase().includes(net.toLowerCase())) &&
          (!statusFilter || row.status === statusFilter),
      ),
    [rows, country, net, statusFilter],
  );

  const openExplain = (s: SteeringScenario) => navigate('/explain', { state: { prefill: scenarioToPrefill(s) } });

  return (
    <div>
      <div className="page-head">
        <h1>Steering Matrix</h1>
        <p>Effective steering per scenario, generated from live evaluation of the NS1 Filter Chain.</p>
      </div>

      {!canExplain && (
        <div className="notice info">
          Steering summary. Full per-scenario evaluation requires the Viewing Engineer role. The scenarios below are the
          steering cases RADAR evaluates.
        </div>
      )}

      <div className="card">
        <div className="filters">
          <label className="field">
            Country
            <input value={country} onChange={(e) => setCountry(e.target.value)} placeholder="IE" />
          </label>
          <label className="field">
            ASN / network
            <input value={net} onChange={(e) => setNet(e.target.value)} placeholder="5466 / Eir" />
          </label>
          <label className="field">
            Evaluation
            <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as '' | Status)}>
              <option value="">All</option>
              <option value="Complete">Complete</option>
              <option value="Partial">Partial</option>
              <option value="Unavailable">Unavailable</option>
            </select>
          </label>
        </div>

        {error && <div className="notice danger">{error}</div>}

        <div className="matrix-wrap">
          <table className="matrix">
            <thead>
              <tr>
                <th>Scenario</th>
                <th>Country</th>
                <th>ASN</th>
                <th>Network</th>
                <th>Prefix condition</th>
                <th>Identity source</th>
                <th>Eligible platforms</th>
                <th>Expected distribution</th>
                <th>Preferred path</th>
                <th>Configured target</th>
                <th>Evaluation</th>
                <th>Provenance</th>
                <th>NS1</th>
              </tr>
            </thead>
            <tbody>
              {!canExplain ? (
                SCENARIOS.map((s) => (
                  <tr key={s.id} style={{ cursor: 'default' }}>
                    <td>{s.label}</td>
                    <td>{s.country}</td>
                    <td>AS{s.asn}</td>
                    <td>{s.network}</td>
                    <td>{s.prefixCondition}</td>
                    <td colSpan={6} className="muted">
                      Requires Viewing Engineer
                    </td>
                    <td>
                      <span className="badge warn">MOCK</span>
                    </td>
                    <td />
                  </tr>
                ))
              ) : rows === null ? (
                <tr>
                  <td colSpan={13} className="center-note">
                    Evaluating scenarios…
                  </td>
                </tr>
              ) : filtered.length === 0 ? (
                <tr>
                  <td colSpan={13} className="center-note">
                    No rows match the current filters.
                  </td>
                </tr>
              ) : (
                filtered.map((row) => {
                  const s = row.scenario;
                  const ev = row.data?.evaluation;
                  const path = networkPathForAsn(s.request.scenario.asn);
                  const partial = row.status !== 'Complete';
                  const dist =
                    !partial && ev?.expectedDistribution
                      ? ev.expectedDistribution.shares
                          .map((x) => `${x.deliveryPlatform ?? x.label} ${(x.share * 100).toFixed(0)}%`)
                          .join(', ')
                      : '—';
                  return (
                    <tr key={s.id} onClick={() => openExplain(s)} title="Open in Explain DNS">
                      <td>{s.label}</td>
                      <td>{s.country}</td>
                      <td>AS{s.asn}</td>
                      <td>{s.network}</td>
                      <td>{s.prefixCondition}</td>
                      <td>{ev ? ev.identity.source : '—'}</td>
                      <td>{ev ? platformLabels(ev, ev.eligibleAnswerIds) : '—'}</td>
                      <td>
                        {dist}
                        {!partial && dist !== '—' && <span className="badge info" style={{ marginLeft: '0.3rem' }}>probabilistic</span>}
                      </td>
                      <td>
                        {path.label} <span className="badge neutral">CONFIGURED</span>
                      </td>
                      <td>
                        {path.label.includes('PNI') ? '70% PNI target' : '—'} <span className="badge neutral">CONFIGURED</span>
                      </td>
                      <td>
                        {row.status === 'Complete' && <span className="badge ok">Complete</span>}
                        {row.status === 'Partial' && <span className="badge warn">Partial</span>}
                        {row.status === 'Unavailable' && <span className="badge danger">Unavailable</span>}
                      </td>
                      <td>{row.data ? <span className="badge warn">{row.data.provenance.synthetic ? 'MOCK · SYNTHETIC' : 'LIVE'}</span> : '—'}</td>
                      <td>
                        <button
                          className="ghost"
                          onClick={(e) => {
                            e.stopPropagation();
                            navigate('/explorer');
                          }}
                        >
                          record
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
        <div className="notice info" style={{ marginTop: '0.75rem' }}>
          Expected shares are <b>probabilistic</b> (weighted shuffle), never a guaranteed traffic split. Partial
          evaluations do not assert a definitive platform. Select a row to open the full Explain DNS view.
        </div>
      </div>
    </div>
  );
}
